---

- hosts: all
  become: true
  
  tasks:
    - name: Install Apache2 & PHP Package
      ansible.builtin.apt:
        name: 
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install Apache2 & PHP Package (RedHat)
      ansible.builtin.command:
        cmd: dnf -y install httpd php update
      when: ansible_os_family == "RedHat"